apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::318010260350:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-YIUJTEAZT0VT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      -system:masters
      rolearn: arn:aws:iam::318010260350:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-18T12:51:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1415"
  uid: 4e9e1577-ab4a-4a9a-b33b-9bea39234fb3
